|  Column name  |  Description  |
| ----- | ------- |
| Num_posts        | Number of total posts that the user has ever posted   |
| Num_following    | Number of following                                   |
| Num_followers    | Number of followers                                   |
| Biography_length | Length (number of characters) of the user's biography |
| Picture_availability | Value 0 if the user has no profile picture, or 1 if has |
| Link_availability| Value 0 if the user has no external URL, or 1 if has |
| Average_caption_length | The average number of character of captions in media |
| Caption_zero     | Percentage (0.0 to 1.0) of captions that has almost zero (<=3) length |
| Non_image_percentage | Percentage (0.0 to 1.0) of non-image media. There are three types of media on an Instagram post, i.e. image, video, carousel
| Engagement_rate_like | Engagement rate (ER) is commonly defined as (num likes) divide by (num media) divide by (num followers)
| Engagement_rate_comment | Similar to ER like, but it is for comments |
| Location_tag_percentage | Percentage (0.0 to 1.0) of posts tagged with location |
| Average_hashtag_count   | Average number of hashtags used in a post |
| Promotional_keywords | Average use of promotional keywords in hashtag, i.e. regrann, contest, repost, giveaway, mention, share, give away, quiz |
| Followers_keywords | Average use of followers hunter keywords in hashtag, i.e. follow, like, folback, follback, f4f|
| Cosine_similarity  | Average cosine similarity of between all pair of two posts a user has |
| Post_interval      | Average interval between posts (in hours) |
| real_fake          | r (real/authentic user), f (fake user/bought followers) |

# Q1: Import labraries

In [1]:
# write your code here ^_^
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
# do not show warnings
import warnings
warnings.filterwarnings("ignore")

# Q2: Read instagram_users.csv file

In [2]:
# write your code here ^_^
file = pd.read_csv('instagram_users.csv')

In [3]:
df=pd.DataFrame(file)
df

Num_posts  Num_following  Num_followers  Biography_length  \
0              44             48            325                33   
1              10             66            321               150   
2              33            970            308               101   
3              70             86            360                14   
4               3             21            285                73   
...           ...            ...            ...               ...   
64239          13            145            642                 0   
64240         652           3000           1300               146   
64241        1500           3700           3200               147   
64242         329           1500           1800               218   
64243         206            659            608                27   

       Picture_availability  Link_availability  Average_caption_length  \
0                         1                  0                      12   
1                         1                  0                     213   
2                         1                  1                     436   
3                         1                  0                       0   
4                         1                  0                      93   
...                     ...                ...                     ...   
64239                     1                  0                       7   
64240                     1                  1                     384   
64241                     1                  1                     129   
64242                     1                  1                     290   
64243                     1                  0                      77   

       Caption_zero  Non_image_percentage  Engagement_rate_like  \
0          0.000000                 0.000              0.000000   
1          0.000000                 1.000             14.390000   
2          0.000000                 1.000             10.100000   
3          1.000000                 0.000              0.780000   
4          0.000000                 0.000             14.290000   
...             ...                   ...                   ...   
64239      0.461538                 0.000             14.270000   
64240      0.000000                 0.389              8.520000   
64241      0.000000                 0.111              9.390000   
64242      0.055556                 0.000              6.350000   
64243      0.000000                 0.333             25.549999   

       Engagement_rate_comment  Location_tag_percentage  \
0                         0.00                    0.000   
1                         1.97                    0.000   
2                         0.30                    0.000   
3                         0.06                    0.000   
4                         0.00                    0.667   
...                        ...                      ...   
64239                     0.58                    0.000   
64240                     0.13                    0.000   
64241                     0.31                    0.722   
64242                     0.26                    0.222   
64243                     0.53                    0.222   

       Average_hashtag_count  Promotional_keywords  Followers_keywords  \
0                      0.000                   0.0               0.000   
1                      1.500                   0.0               0.000   
2                      2.500                   0.0               0.056   
3                      0.000                   0.0               0.000   
4                      0.000                   0.0               0.000   
...                      ...                   ...                 ...   
64239                  0.077                   0.0               0.000   
64240                  1.611                   0.0               0.000   
64241                  0.000                   0.0               0.056   
64242                  0.500        

# Q3: Split tha dataset into training and testing

In [4]:
# write your code here ^_^
#data
x = df.drop(['real_fake'], axis=1)
#target
y = df['real_fake']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

# Q4: Build three machine models 

## Q4.1: The first machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [8]:
# write your code here ^_^
rfmodel = RandomForestClassifier()
print(rfmodel )

RandomForestClassifier()


In [9]:
rfmodel.fit(x_train, y_train);
ypredict = rfmodel.predict(x_test)

In [10]:
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=rfmodel.predict(x_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=ypredict))

Train data accuracy: 0.9999777629530798
Test data accuracy: 0.898256718895922


In [11]:
#Confusion Matrix
print("Confusion Matrix for traning data")
print(confusion_matrix(y_train,rfmodel.predict(x_train)))
print("Confusion Matrix for test data")
print(confusion_matrix(y_test,ypredict))

Confusion Matrix for traning data
[[22268     0]
 [    1 22701]]
Confusion Matrix for test data
[[7968 1548]
 [ 413 9345]]


## Q4.2: The second machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [12]:
# write your code here ^_^
lmodel = LogisticRegression()
print(lmodel)

LogisticRegression()


In [13]:
lmodel.fit(x_train,y_train)
lypredict = lmodel.predict(x_test)

In [14]:
# predict accuracy score
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=lmodel.predict(x_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=lypredict))

Train data accuracy: 0.7616633311096287
Test data accuracy: 0.7602988481892705


In [15]:
#Confusion Matrix
print("Confusion Matrix for traning data")
print(confusion_matrix(y_train,lmodel.predict(x_train)))
print("Confusion Matrix for test data")
print(confusion_matrix(y_test,lypredict))

Confusion Matrix for traning data
[[15523  6745]
 [ 3973 18729]]
Confusion Matrix for test data
[[6614 2902]
 [1718 8040]]


## Q4.3: The third machine model
- Print the model's name.
- Print the model's accuracy.
- Print the model's confusion matrix.

In [16]:
# write your code here ^_^
dtmodel = DecisionTreeClassifier()
print(dtmodel)

DecisionTreeClassifier()


In [17]:
dtmodel.fit(x_train,y_train)
dtypredict = dtmodel.predict(x_test)

In [18]:
# predict accuracy score
print("Train data accuracy:",accuracy_score(y_true = y_train, y_pred=dtmodel.predict(x_train)))
print("Test data accuracy:",accuracy_score(y_true = y_test, y_pred=dtypredict))

Train data accuracy: 0.9999777629530798
Test data accuracy: 0.8517692227871745


In [19]:
#Confusion Matrix
print("Confusion Matrix for traning data")
print(confusion_matrix(y_train,dtmodel.predict(x_train)))
print("Confusion Matrix for test data")
print(confusion_matrix(y_test,dtypredict))

Confusion Matrix for traning data
[[22268     0]
 [    1 22701]]
Confusion Matrix for test data
[[8134 1382]
 [1475 8283]]
